package com.apero.testai.utils.beauty_full

import com.apero.beauty_full.api.config.ads.VslBeautyFullAllFeatureAdsIdConfig

class VslBeautyFullAdsConfig : VslBeautyFullAllFeatureAdsIdConfig {
    override val rewardGenAllFeatureHigh: String = "ca-app-pub-xxx/reward_high"
    override val rewardGenAllFeatureNormal: String = "ca-app-pub-xxx/reward_normal"
    override val idBannerAllFeatureHigh: String = "ca-app-pub-xxx/banner_all_high"
    override val idBannerAllFeatureNormal: String = "ca-app-pub-xxx/banner_all_normal"
    override val idBannerShareHigh: String = "ca-app-pub-xxx/banner_share_high"
    override val idBannerShareNormal: String = "ca-app-pub-xxx/banner_share_normal"
    override val idBannerStyleHigh: String = "ca-app-pub-xxx/banner_style_high"
    override val idBannerStyleNormal: String = "ca-app-pub-xxx/banner_style_normal"
    override val idNativeHighFloor: String = "ca-app-pub-xxx/native_high_floor"
    override val idNativeNormalFloor: String = "ca-app-pub-xxx/native_normal_floor"
    override val idInterstitialHighPriority: String = "ca-app-pub-xxx/interstitial_high"
    override val idInterstitialMediumPriority: String = "ca-app-pub-xxx/interstitial_medium"
    override val idInterstitialLowPriority: String = "ca-app-pub-xxx/interstitial_low"
    override val idRewardGenRestoreHigh: String = "ca-app-pub-xxx/reward_restore_high"
    override val idRewardGenRestoreNormal: String = "ca-app-pub-xxx/reward_restore_normal"
    override val idBannerAdStyleHigh: String = "ca-app-pub-xxx/banner_ad_style_high"
    override val idBannerAdStyleNormal: String = "ca-app-pub-xxx/banner_ad_style_normal"
    override val idRewardGenTemplateHigh: String = "ca-app-pub-xxx/reward_template_high"
    override val idRewardGenTemplateNormal: String = "ca-app-pub-xxx/reward_template_normal"
    override val idBannerTemplateHigh: String = "ca-app-pub-xxx/banner_template_high"
    override val idBannerTemplateNormal: String = "ca-app-pub-xxx/banner_template_normal"
    override val idBannerArtHigh: String = "ca-app-pub-xxx/banner_art_high"
    override val idBannerArtNormal: String = "ca-app-pub-xxx/banner_art_normal"
    override val idRewardGenArtHigh: String = "ca-app-pub-xxx/reward_gen_art_high"
    override val idRewardGenArtNormal: String = "ca-app-pub-xxx/reward_gen_art_normal"
    override val idRewardGenArtPremiumHigh: String = "ca-app-pub-xxx/reward_gen_art_premium_high"
    override val idRewardGenArtPremiumNormal: String = "ca-app-pub-xxx/reward_gen_art_premium_normal"
    override val idBannerArtPremiumHigh: String = "ca-app-pub-xxx/banner_art_premium_high"
    override val idBannerArtPremiumNormal: String = "ca-app-pub-xxx/banner_art_premium_normal"
    override val idBannerRemoveBgHigh: String = "ca-app-pub-xxx/banner_remove_bg_high"
    override val idBannerRemoveBgNormal: String = "ca-app-pub-xxx/banner_remove_bg_normal"
    override val idRewardGenRemoveBgHigh: String = "ca-app-pub-xxx/reward_gen_remove_bg_high"
    override val idRewardGenRemoveBgNormal: String = "ca-app-pub-xxx/reward_gen_remove_bg_normal"
} 